# ruff.toml
line-length = 88
target-version = "py310"

[lint]
select = ["ALL"] # or use a strict curated list like ["F", "E", "I", "UP", "C90", "B", "A", "PL"]
ignore = ["D203", "D212"] # optional: e.g., conflicting docstring rules

[format]
quote-style = "double"
indent-style = "space"
