"""
This type stub file was generated by pyright.
"""

def sendobj(self, obj): # -> None:
    """
        Atomically send a BSON message.
    """
    ...

def recvobj(self): # -> _EmptyClass | list[Any] | dict[Any, Any] | None:
    """
        Atomic read of a BSON message.

        This function either returns a dict, None, or raises a socket error.

        If the return value is None, it means the socket is closed by the other side.
    """
    ...

def recvbytes(self, bytes_needed, sock_buf=...): # -> BytesIO | None:
    """
        Atomic read of bytes_needed bytes.

        This function either returns exactly the nmber of bytes requested in a
        StringIO buffer, None, or raises a socket error.

        If the return value is None, it means the socket is closed by the other side.
    """
    ...

