"""
This type stub file was generated by pyright.
"""

from datetime import tzinfo

"""Timezone related utilities for BSON."""
ZERO = ...
class FixedOffset(tzinfo):
    """Fixed offset timezone, in minutes east from UTC.

    Implementation based from the Python `standard library documentation
    <http://docs.python.org/library/datetime.html#tzinfo-objects>`_.
    Defining __getinitargs__ enables pickling / copying.
    """
    def __init__(self, offset, name) -> None:
        ...
    
    def __getinitargs__(self): # -> tuple[timedelta, Any]:
        ...
    
    def utcoffset(self, dt): # -> timedelta:
        ...
    
    def tzname(self, dt): # -> Any:
        ...
    
    def dst(self, dt): # -> timedelta:
        ...
    


utc = ...
